### ISSUE TITLE
useDocuments(query) doesn't always update on deletions, because of paths() query limits

### ISSUE THREAD

**Issue by cinnamon-bun** [earthstar-project/react-earthstar#61]
## Problem

Deleting a document doesn't always trigger useDocuments to re-render the component.

## Reason

*I think* it's because...

It subscribes to storage events here...

https://github.com/earthstar-project/react-earthstar/blob/b2de2580cab6fa645ed9c9762f6ed5f8b76ffea1/src/hooks.tsx#L415-L422

It uses path queries to detect when things have changed.

But some kinds of queries are not supported on path queries... like `contentLength`.  Those are just ignored when doing the path query.

## My code that triggers this bug

In my code I'm doing a query to get all documents except deleted documents (which have content length zero):

https://github.com/cinnamon-bun/buntimer-earthstar/blob/0e8f0555955f4c9a5e65a221c423f46c9114680a/src/buntimer.tsx#L89-L96

```ts
    let query: Query = {
        pathStartsWith: '/buntimer-v1/timers/common/',
        pathEndsWith: '.json',
        contentLengthGt: 0,  // <--------
    }
```

When I delete a document, the hook does not re-render.

If I remove `contentLengthGt` from the query and manually filter out the deleted documents later on, it **does** re-render.

## Why path queries work this way

For efficiency, path queries can only look at the path itself, they can't look at document content or timestamps or anything else.

In the Query type, we've separated out the safe kinds of queries that only apply to paths...

https://github.com/earthstar-project/earthstar/blob/main/src/storage/query.ts#L39-L56

```ts
export interface Query {
    //=== filters that affect all documents equally within the same path  <------
    path?: string,
    pathStartsWith?: string,
    pathEndsWith?: string,
```

...And these are the other filters that can't be used in path queries.
```ts
    //=== filters that differently affect documents within the same path  <-----
    timestamp?: number,
    timestampGt?: number,
    timestampLt?: number,
    author?: AuthorAddress,
    contentLength?: number,
    contentLengthGt?: number,
    contentLengthLt?: number,
```

## Solutions?

I guess we need to not use `paths()` queries inside `useDocuments` to tell if things have changed.

In the meantime, I worked around the problem by limiting my query to just the path-related filters and doing further filtering myself in javascript.

**Comment by cinnamon-bun** [comment]
There's a deeper challenge here in getting notifications about query results...

When a document changes and drops out of the query results, we need to know... so the `onWrite` callback from earthstar core needs to tell us the old document as well as the new one.

Otherwise we have to re-run the whole query on every single `onWrite` :(

**Comment by sgwilym** [comment]
The problem mentioned in cinnamon's issue above is also a problem for https://github.com/earthstar-project/earthstar/issues/110 and https://github.com/earthstar-project/earthstar/issues/113
