### ISSUE TITLE
FocusSyncer is triggered multiple times at once when switching back to a tab

### ISSUE THREAD

**Issue by cinnamon-bun** [earthstar-project/react-earthstar#62]
https://github.com/earthstar-project/react-earthstar/blob/2d3b067c572970b80f0fd73fe3ae6667f3823dd8/src/components/_FocusSyncer.tsx

I'm not sure why yet, but if you switch away from an Earthstar app and switch back, FocusSyncer triggers several simultaneous syncs.  This can be seen in the console as well as the network requests.

Buntimer is a nice simple app to try this out with, since it doesn't have any built-in timed document updating like Status does to confuse things.  https://buntimer-earthstar.netlify.app/

**Comment by cinnamon-bun** [comment]
FocusSyncer also runs once when the page first loads, but only one set of network requests is triggered at that time, so that must be fine.

I thought that OnePubOneWorkspaceSyncer was supposed to prevent this kind of problem from happening, I'm not sure where things are going wrong yet.

**Comment by sgwilym** [comment]
Maybe `visibilitychange` should not be included here, as I guess that triggers when you switch _away_ from a tab as well.

On Safari, I see syncing triggered four times when returning to a tab. I'd guess that's:

1. Upon switching away, `visibilitychange` fires
2. Upon returning, 'visiblitychange` fires again
3. As does `focus`.

So where is that fourth event coming from? When I do the same thing in the Earthbar example I see three firings per tab switch. 🤔

**Comment by cinnamon-bun** [comment]
The syncer tries to not run multiple times at once.  It doesn't seem to do a good job, but it might be absorbing some of the multiple runs.

Might need to add more `console.log`s to the FocusSyncer to see when it's attempting to sync, to see what's really happening.
